# Generated by Django 5.2 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companyregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecompany', models.CharField(max_length=50)),
                ('gstid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('comapanytype', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('resume', models.FileField(upload_to='media/')),
                ('photo', models.ImageField(upload_to='media/')),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
