# Generated by Django 5.2.1 on 2025-05-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
    ]
